kind: pipeline
name: default

steps:
  - name: prepare
    image: busybox
    commands:
      - mkdir -p /cache/${DRONE_REPO}/docker
    volumes:
      - name: cache
        path: /cache

  - name: build-wisdom-service
    image: plugins/docker
    settings:
      repo: mejlholm/wisdom-service
      username:
        from_secret: docker_hub_username
      password:
        from_secret: docker_hub_password
      dockerfile: wisdom-service/Dockerfile
      context: wisdom-service
      tags:
        - latest
        - 2.0.${DRONE_BUILD_NUMBER}
      use_cache: true

  - name: build-wisdom-frontend
    image: plugins/docker
    settings:
      repo: mejlholm/wisdom-frontend
      username:
        from_secret: docker_hub_username
      password:
        from_secret: docker_hub_password
      dockerfile: wisdom-frontend/Dockerfile
      context: wisdom-frontend
      tags:
        - latest
        - 2.0.${DRONE_BUILD_NUMBER}
      use_cache: true

  - name: notify
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
    depends_on:
      - build-wisdom-service
      - build-wisdom-frontend

trigger:
  event:
    exclude:
    - tag

volumes:
  - name: cache
    host:
      path: /var/cache
  - name: docker
    host:
      path: /var/cache/${DRONE_REPO}/docker