---
kind: Deployment
apiVersion: apps/v1beta2
metadata:
  name: wisdom-service
  namespace: apps
  labels:
    app: wisdom-service
  annotations:
    fluxcd.io/tag.wisdom-frontend: glob:2.*
    fluxcd.io/automated: 'true'
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wisdom-service
  template:
    metadata:
      name: wisdom-service
      labels:
        app: wisdom-service
      annotations:
        linkerd.io/inject: enabled
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8081'
    spec:
      containers:
      - name: wisdom-service
        image: mejlholm/wisdom-service:2.0.54
        envFrom:
        - secretRef:
            name: wisdom-service-secret
        resources:
          limits:
            memory: "256Mi"
        env:
        - name: JAEGER_ENDPOINT
          value: 'http://jaeger-collector.monitoring:14268/api/traces'
        - name: JAEGER_SAMPLER_TYPE
          value: 'const'
        - name: JAEGER_SAMPLER_PARAM
          value: '1'
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health/live
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health/ready
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 1
          periodSeconds: 1
          successThreshold: 2
          timeoutSeconds: 5
